services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/phoenix_test_dev
      - SECRET_KEY_BASE=insecure_key_for_dev_only
      - PHX_HOST=localhost
      - PORT=4000
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: sh
  
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phoenix_test_dev
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: